### ISSUE TITLE
immediate explosion of grenade when killed while holding a ticking grenade regardless of how much time is left

### ISSUE THREAD

**Issue by rtcw-nihi** [rtcw-nihi/ospx#1]
If you are killed while priming a grenade then it seems to explode immediately.  It should drop and explode according to the grenade timer (i.e. the same time as if you were not killed).

**Comment by krazykaze81** [comment]
Bug still exists

https://streamable.com/znoglf

**Comment by krazykaze81** [comment]
Found this code in player_die - could be our problem

// JPW NERVE -- if player is holding ticking grenade, drop it
	if ( g_gametype.integer != GT_SINGLE_PLAYER ) {
		if ( ( self->client->ps.grenadeTimeLeft ) && ( self->s.weapon != WP_DYNAMITE ) ) {
			launchvel[0] = crandom();
			launchvel[1] = crandom();
			launchvel[2] = random();
			VectorScale( launchvel, 160, launchvel );
			VectorCopy( self->r.currentOrigin, launchspot );
			launchspot[2] += 40;
			fire_grenade( self, launchspot, launchvel, self->s.weapon );

		}
	}

**Comment by krazykaze81** [comment]
Fixed in player_die

`// JPW NERVE -- if player is holding ticking grenade, drop it
if ( g_gametype.integer != GT_SINGLE_PLAYER ) {
if ( ( self->client->ps.grenadeTimeLeft ) && ( self->s.weapon != WP_DYNAMITE ) ) {
launchvel[0] = crandom();
launchvel[1] = crandom();
launchvel[2] = random();
VectorScale( launchvel, 160, launchvel );
VectorCopy( self->r.currentOrigin, launchspot );
launchspot[2] += 40;
fire_grenade( self, launchspot, launchvel, self->s.weapon )**->damage = 0; // nobo fix from RtcwPub**
