### ISSUE TITLE
Stats not resetting at end of the round

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#177]
Player stats continue to accumulate round to round in some cases.  In some cases gibs only

https://cdn.discordapp.com/attachments/702195723357126746/786827995918106635/gibs.jpg

**Comment by rtcw-nihi** [comment]
Fixed the gibs issue: https://github.com/rtcw-nihi/ospx/commit/4a52a686ab604d3111cd73f2cc7094a2c36745de
It was not that it wasn't getting reset but it was accumulating gibs during warmup rounds.
 
I believe other stats could have accumulated due to someone issuing a "map_restart" during a match.  If we see this again (w/o "map_restart") or in the unlikely case that it is desired to reset stats on 'map_restart' then we should open a new issue.
