### ISSUE TITLE
Antilag

### ISSUE THREAD

**Issue by rtcw-nihi** [rtcw-nihi/ospx#2]
Antilag needs improvement.  A painful task that is difficult to test (for me at least).

**Comment by krazykaze81** [comment]
I ported the antilag branch into develop - unlagged code from 1.0 - needs to be tested.  Comments from @S4NDM4NN on using unlagged2 vs unlagged (rtcw 1.0) 

S4NDM4NN_07/20/2020
antilag from rtcw 1.0 is using unlagged code, so I dont know how much of a difference it could make.
atleast I am pretty sure that is where I originally found the code. It is probably not unlagged 2.0 since in unlagged 2.0 I think mostly they changed the client side stuff to make dodging rockets and drawing rails more accurate in q3
I do not think that the unlagged code should be that hard to add to RTCW though. Mainly just need the time to digest it, right now I dont have a lot of time

**Comment by krazykaze81** [comment]
Antilag has been added and currently being tested
