### ISSUE TITLE
Add objective stats

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#46]
Record objective stats - we can track doc grabs, flag grabs, doc returns, doc runner killer, etc

**Comment by rtcw-nihi** [comment]
Pretty much this was all done in 1.1 (or 1.0.1) except for "drop obj". This was added: https://github.com/rtcw-nihi/ospx/commit/544f2a819e1412f32da852622e3d60c5e17dcde9.  I imagine we can continue adding more (as well as more detail to each event) but for now, I'd say this issue is closed.  Let's open a new one for ideas or desired event info.
